/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.dovydasvenckus.web.scrapper.client

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
